### ISSUE TITLE
Windows 7  sublime maven bug

### ISSUE THREAD

**Issue by ideat0r** [nlloyd/SublimeMaven#11]
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\maven.py", line 174, in run
  File ".\maven.py", line 189, in on_done
  File ".\maven.py", line 84, in **init**
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 5: ordinal not in range(128)

**Comment by ideat0r** [comment]
Fixed. Just change line 84 in maven.py to:
proc_env[k] = os.path.expandvars(v.decode(sys.getfilesystemencoding())).encode(sys.getfilesystemencoding())

**Comment by nlloyd** [comment]
Just applied the fix, tyvm!
