### ISSUE TITLE
Linux Machine - no module utils

### ISSUE THREAD

**Issue by jrock2004** [nlloyd/SublimeMaven#23]
Trying to use this on a Linux Machine (Linux Mint). Here is the stack in subl 3 

reloading plugin SublimeMaven.config_generator
reloading plugin SublimeMaven.import
Traceback (most recent call last):
  File "/home/jcostanzo/bin/sublime_text_3/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/home/jcostanzo/bin/sublime_text_3/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "import in /home/jcostanzo/.config/sublime-text-3/Installed Packages/SublimeMaven.sublime-package", line 26, in <module>
ImportError: No module named 'utils'
reloading plugin SublimeMaven.maven
Traceback (most recent call last):
  File "/home/jcostanzo/bin/sublime_text_3/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/home/jcostanzo/bin/sublime_text_3/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "maven in /home/jcostanzo/.config/sublime-text-3/Installed Packages/SublimeMaven.sublime-package", line 288
    print self.last_str
             ^
SyntaxError: invalid syntax

**Comment by nlloyd** [comment]
This looks to be related to issue 22. I am working on this now.

**Comment by nlloyd** [comment]
This should now be fixed. Let me know if this is not the case.
